// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0gpkPyAGQWmbifvZZNVOFf7be8VRj3Y0',
    appId: '1:182751052690:web:0d0e27a47e144dc619374b',
    messagingSenderId: '182751052690',
    projectId: 'nomad-a87a1',
    authDomain: 'nomad-a87a1.firebaseapp.com',
    storageBucket: 'nomad-a87a1.appspot.com',
    measurementId: 'G-0198T6BJR8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCARUTPo0vmk6C9aL0eke2RH0b4j9F4ywM',
    appId: '1:182751052690:android:fe9ff51868495ba919374b',
    messagingSenderId: '182751052690',
    projectId: 'nomad-a87a1',
    storageBucket: 'nomad-a87a1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZMNWNWVnF1ArBSjXxk-vqM4oFUVs8SdA',
    appId: '1:182751052690:ios:b3d66938a9663ffd19374b',
    messagingSenderId: '182751052690',
    projectId: 'nomad-a87a1',
    storageBucket: 'nomad-a87a1.appspot.com',
    iosBundleId: 'com.example.final0924',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZMNWNWVnF1ArBSjXxk-vqM4oFUVs8SdA',
    appId: '1:182751052690:ios:d8a62747fae2142819374b',
    messagingSenderId: '182751052690',
    projectId: 'nomad-a87a1',
    storageBucket: 'nomad-a87a1.appspot.com',
    iosBundleId: 'com.example.final0924.RunnerTests',
  );
}
